### ISSUE TITLE
musik wird ein zweites mal gestartet wenn man stirbt

### ISSUE THREAD

**Issue by valueerrorx** [valueerrorx/attm#18]

**Comment by europagymnasium** [comment]
Greatings Summoner!
This is not a bug, it's a feature.

**Comment by europagymnasium** [comment]
Danke das Sie uns Kontaktiert haben, aber leider haben wir derzeit keine Lust uns darum zu kümmern. Vielen Dank für ihr Verständnis.

**Comment by europagymnasium** [comment]
-
