### ISSUE TITLE
moving platform:  ermögliche horizontale bewegung der plattformen 

### ISSUE THREAD

**Issue by valueerrorx** [valueerrorx/attm#25]
im tiled editor kann man objekten namen geben.  
über object.sprite.name kann man diesen abrufen "horziontal" "vertikal" und dementsprechend den tween anderes aufstellen

**Comment by europagymnasium** [comment]
niklas

**Comment by europagymnasium** [comment]
in tiled: name=vertical 
sonst wird horizontal
