### ISSUE TITLE
go fullscreen ist im toggle modus unbrauchbar

### ISSUE THREAD

**Issue by valueerrorx** [valueerrorx/attm#37]
die funktion gofull() sollte bei einmaligem klick im menü aufgerufen werden und in jedem fall nur auf fullscreen schalten.

wenn diese funktion auch wieder zurückschaltet in den windowed mode kann kein level betreten werden ohne fullscreen zu verlassen

**Comment by mischnic** [comment]
niklas

**Comment by europagymnasium** [comment]
Thomas und Adrian

**Comment by europagymnasium** [comment]
Thomas und Adrian

**Comment by mischnic** [comment]
niklas
